volumes:
  mysql_data:
    driver: local
networks:
  local-dev:    
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - local-dev
    volumes:
      - type: bind
        source: ./service
        target: /service
    depends_on:
      - db
    tty: true
  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    networks:
      - local-dev
    volumes:
      - type: bind
        source: "mysql_data"
        target: "/var/lib/mysql"
