volumes:
  mysql_data:
networks:
  local-dev:    
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - local-dev
    volumes:
      - type: bind
        source: ./service
        target: /service